### ISSUE TITLE
Getting generic error message: No configuration setting found for key 'play' on every config issue

### ISSUE THREAD

**Issue by tenstriker** [play2-maven-plugin/play2-maven-plugin#158]
I initially opened this case for PlayFramework but they think it may be because of the way play2-maven-plugin is loading the play server. Here's the link to that issue:
https://github.com/playframework/playframework/issues/8058#issuecomment-348389031

Detail:

Play Version (2.6.6 or 2.6.7)

API (Scala 2.11.11)

JDK (Oracle 1.8.0_72)

Play Maven Plugin Version - 1.0.0-rc1

Following stacktrace bleeds on log in multiple situation. I have seen it on hot reload error due to compilation issue, missing configuration, when Modules or Routers are not loaded, Dependencies are missing or conflicting.
Sometime hitting the same url gives different error message and that can actually point to real issue but it shouldn't be the case. Hitting same url should be idempotent as far as play framework is concern.

I think is very misleading to use this stacktrace which doesn't pin point any issue. Proper error should catch via responsible component and emits meaningful error messages.

e.g. For compilation issue on hot reload, it shouldn't even try to refresh application and just emit compilation errors
For missing configuration, it should be able to tell what key is missing. I don't see in such key or variable as 'play' in my application.conf. If it's internal present the documentation on that.
For missing modules or routes definition give user a WARN messages
For missing dependencies give a meaningful error message in first place.

com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'play'
at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264)
at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270)
at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
at play.api.ConfigLoader$$anonfun$36$$anonfun$apply$34.apply(Configuration.scala:1065)
at play.api.ConfigLoader$$anonfun$36$$anonfun$apply$34.apply(Configuration.scala:1065)
at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1021)
at play.api.ConfigLoader$$anon$2.load(Configuration.scala:1013)
at play.api.Configuration.get(Configuration.scala:214)
at play.core.server.common.ForwardedHeaderHandler$ForwardedHeaderHandlerConfig$.apply(ForwardedHeaderHandler.scala:233)
at play.core.server.common.ReloadCache.reloadForwardedHeaderHandler(ReloadCache.scala:74)
at play.core.server.AkkaHttpServer$$anon$3.reloadValue(AkkaHttpServer.scala:170)
at play.core.server.AkkaHttpServer$$anon$3.reloadValue(AkkaHttpServer.scala:167)
at play.core.server.common.ReloadCache$$anonfun$1.apply(ReloadCache.scala:25)
at play.core.server.common.ReloadCache$$anonfun$1.apply(ReloadCache.scala:25)
at play.utils.InlineCache.fresh(InlineCache.scala:69)
at play.utils.InlineCache.apply(InlineCache.scala:55)
at play.core.server.common.ReloadCache.cachedFrom(ReloadCache.scala:31)
at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$modelConversion(AkkaHttpServer.scala:183)
at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:189)
at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:743)
at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
at akka.actor.ActorCell.invoke(ActorCell.scala:496)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Steps to reproduce:

It is been tested only with Play-maven projects as that is what I am trying to build on:

Download play-scala-rest-api from here: https://github.com/playframework/play-scala-rest-api-example
Disable Module from applicaiton.conf : play.modules.disabled += "Module"
Run server using mvn play2:run
Hit any url on server. e.g. http:localhost:9000
Another way to reproduce:

Download play-scala-rest-api from here: https://github.com/playframework/play-scala-rest-api-example
Keep the Module enabled in applicaiton.conf : play.modules.enabled += "Module"
Change PostResoureHandler definition to add WSClient dependency.
class PostResourceHandler @Inject()(
ws: WSClient,
routerProvider: Provider[PostRouter],
postRepository: PostRepository)(implicit ec: ExecutionContext)
Add play-ws dependency suggested on play-maven site.

com.typesafe.play
play-ws_${play2-scala.version}
${play2.version}
Run server using mvn play2:run
Hit any url on server. e.g. http:localhost:9000

**Comment by gslowikowski** [comment]
Thank you for reporting. I will look at this problem soon.

**Comment by gslowikowski** [comment]
This problem was "introduced" by https://github.com/playframework/playframework/pull/7644.

Before this change, build was executed [in separate thread](https://github.com/playframework/playframework/blob/2.6.1/framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala#L117-L123).
Since applying this PR, the build is executed in request handling thread (`netty-event-loop-<n>` in Netty and `play-dev-mode-akka.actor.default-dispatcher-<n>` in Akka Http).

This change revealed a problem with Maven. It [changes the classloader](https://github.com/apache/maven/blame/maven-3.1.0/maven-core/src/main/java/org/apache/maven/lifecycle/internal/BuildListCalculator.java#L58) of the thread, which executes the build.
Previously this thread was created exclusively for the build purpose, so it wasn't a problem.
Now it's a request handling thread with the class path containing all required classes and resources.
After the class loader change, Play! cannot find configuration resource, because it's not on the class path anymore.

The fix will be simple - backup the original class loader and restore it after Maven build execution.

**Comment by gslowikowski** [comment]
New `1.0.0-rc2-SNAPSHOT` snapshot deployed.

I will try to release `1.0.0-rc2` ASAP.

**Comment by gslowikowski** [comment]
Version `1.0.0-rc2` released.
