### ISSUE TITLE
Static routesGenerator does not run

### ISSUE THREAD

**Issue by Methrat0n** [play2-maven-plugin/play2-maven-plugin#192]
I am migrating a project from sbt to maven. This plugin seems great and thanks for all your work, but I can't run or install.

The plugin's part of the pom.xml :
```
<plugin>
  <groupId>com.google.code.play2-maven-plugin</groupId>
  <artifactId>play2-maven-plugin</artifactId>
  <version>${play2.plugin.version}</version>
  <extensions>true</extensions>
  <configuration>
    <routesGenerator>static</routesGenerator>
    <serverJvmArgs>-Dplay.evolutions.db.default.autoApply=true</serverJvmArgs>
    <mainModule>lifecycle-application:lifecycle-application_2.12</mainModule>
  </configuration>
</plugin>
```
As you can see, it's part of a multi-modules project.

The first problem I encounter is that the routes files are compiled to Scala, but are not added to the classpath. I work-around this using build-helper-maven-plugin. The second problem, for which I have not found a solution, is that the generated Routes.scala calls an inexisting function : 
`
error: value concatPrefix is not a member of object play.api.routing.Router
`
I am not sure why this is happenning (maybe a wrong play version is selected ?). What I can say is that compiling the project with sbt does not give me this problem (the function call is stricly different).

I have search for an example of static routes generation here : 
https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/test-projects-1.0.0-rc5/play26/scala

But I can't find any. If I am doing something wrong please point me out.

**Comment by gslowikowski** [comment]
Hi @Methrat0n 

Your configuration is OK, static router should be generated. Static router was the default one up to Play! 2.4.x, check [play24](https://github.com/play2-maven-plugin/play2-maven-test-projects/tree/test-projects-1.0.0-rc5/play24) test projects.

Directory containing generated router files is added to source roots (check [here](https://github.com/play2-maven-plugin/play2-maven-plugin/blob/play2-1.0.0-rc5/play2-maven-plugin/src/main/java/com/google/code/play2/plugin/Play2RoutesCompileMojo.java#L243)). Build helper is not needed. Something else must be the problem.

I need a simple example project to be able to help you with Routes.scala compilation problem.

**Comment by Methrat0n** [comment]
Here is an example project :
https://github.com/Methrat0n/play2-maven-router-error
The first commit is without build-helper-maven-plugin, the second use it to add the routes directory.

After seeing the errors again I come to think it's a classpath problem. The generated files seems without classpath.

I made a simpler project work. It was before I add the `->` in the routes files and split the project into dependant modules.

Also, I am sorry : I made a mistake. I do not want to use the generated router. I was trying things out and at this point it seems closer to what I was excpeting. This example project is without static router configuration.

I hope this will help you.

**Comment by gslowikowski** [comment]
Thanks for example project.

Unfortunately, I see several different problems in your project.

If you don't want to generate router, you don't need `*.routes` files, right? But you are referencing `Routes` class in `OneComponents` and `TwoComponents` classes. How can they be compiled if there are no `Routes` classes generated.

Another problem - how can you reference `OneComponents` and `TwoComponents` classes from `ApplicationComponents` without imports?

Additionally, I see that Play adds unused imports to generated router files. This generates warnings during compilation, but with `-Xfatal-warnings` flag they become errors. Is this the reason, why you don't want to generate routers?

Is this project buildable? Please, add working SBT build, I will convert it into Maven one and explain all differences.

**Comment by Methrat0n** [comment]
I may have been unclear in my last post, but I do want to generate router. The static part of this issue was a mistake.

Also, It's true I made mistakes in the previous version of the code due to the impossibility to actually build. I am truly sorry about this and provide the sbt build bersion as you ask. It's on the same repo.

I am grateful for your help, thank's in advance for converting this build.

**Comment by Methrat0n** [comment]
After some more investigations I can now state that the problem is about the `->` symbol in routes file. A simple module project without it does work as expected, and neither a multi-module nor a simple module project with it work. 
In the last commit of my example project, you can find a simple project (finale) which does an internal `->` and cant resolve the classpath in the generated routes.

**Comment by gslowikowski** [comment]
I don't have much time. [Here](https://github.com/gslowikowski/play2-maven-router-error/tree/solution-2) and [here](https://github.com/gslowikowski/play2-maven-router-error/tree/solution-1) are two alternative solutions with and without using `play` packaging.

Maven plugin doesn't support overriding roures imports completely, only adding to default ones. I'll think about adding this functionality soon. For now I had to remove `-Xfatal-warnings` from `scalacOptions`.

**Comment by Methrat0n** [comment]
I tried to launch the first project using `mvn clean play2:routes-compile play2:run`
But it give me the same errors.
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[7,12] cannot find symbol
  symbol:   class RoutesPrefix
  location: package test
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[11,39] cannot find symbol
  symbol:   class ReverseStatusController
  location: package test.controllers
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[15,52] package test.controllers.javascript does not exist
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[11,103] cannot find symbol
  symbol:   class ReverseStatusController
  location: package test.controllers
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[11,128] cannot find symbol
  symbol:   variable RoutesPrefix
  location: class test.controllers.routes
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[15,127] package test.controllers.javascript does not exist
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main/test/controllers/routes.java:[15,152] cannot find symbol
  symbol:   variable RoutesPrefix
  location: class test.controllers.routes.javascript
```

**Comment by gslowikowski** [comment]
It works for me (`mvn clean play2:run` is enough).

Did you disable `maven-compiler-plugin` (with two skip parameters)? If yes, show me full stack trace.

**Comment by Methrat0n** [comment]
I re-clone the repo, the rest is in the stack : 
```
mvn clean play2:run
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] example
[INFO] module.two
[INFO] module.one
[INFO] module.finale
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building example 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ static.function.call ---
[INFO]
[INFO] --- play2-maven-plugin:1.0.0-rc5:run (default-cli) @ static.function.call ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building module.two 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ module.two ---
[INFO]
[INFO] --- play2-maven-plugin:1.0.0-rc5:run (default-cli) @ module.two ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building module.one 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ module.one ---
[INFO]
[INFO] --- play2-maven-plugin:1.0.0-rc5:run (default-cli) @ module.one ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building module.finale 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ module.finale ---
[INFO]
[INFO] --- play2-maven-plugin:1.0.0-rc5:run (default-cli) @ module.finale ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.code.play2.watcher.jnotify.JNotifyFileWatchService (file:/Users/merlin/.m2/repository/com/google/code/play2-maven-plugin/play2-source-watcher-jnotify/1.0.0-rc5/play2-source-watcher-jnotify-1.0.0-rc5.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of com.google.code.play2.watcher.jnotify.JNotifyFileWatchService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[INFO]
[INFO] (Server started, use [Enter] to stop...)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] example
[INFO] module.finale
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building example 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (default) @ static.function.call ---
[INFO] Source directory: /Users/merlin/dev/play2-maven-router-error/target/routes/main added.
[INFO]
[INFO] --- sbt-compiler-maven-plugin:1.0.0:compile (default-sbt-compile) @ static.function.call ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building module.finale 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (default) @ module.finale ---
[INFO] Source directory: /Users/merlin/dev/play2-maven-router-error/module.finale/target/routes/main added.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ module.finale ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ module.finale ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- sbt-compiler-maven-plugin:1.0.0:compile (default-sbt-compile) @ module.finale ---
[INFO] Compiling 3 Scala sources to /Users/merlin/dev/play2-maven-router-error/module.finale/target/classes...
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/src/main/scala/test/ApplicationComponents.scala:5: object intern is not a member of package test
[ERROR] import test.intern.{Routes => InternRoutes}
[ERROR]             ^
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/src/main/scala/test/ApplicationComponents.scala:16: not found: type InternRoutes
[ERROR]   val testRouter: InternRoutes = new InternRoutes(
[ERROR]                   ^
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/src/main/scala/test/ApplicationComponents.scala:16: not found: type InternRoutes
[ERROR]   val testRouter: InternRoutes = new InternRoutes(
[ERROR]                                      ^
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/src/main/scala/test/ApplicationComponents.scala:21: not found: type Routes
[ERROR]   override val router: Routes = new Routes(
[ERROR]                        ^
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/src/main/scala/test/ApplicationComponents.scala:21: not found: type Routes
[ERROR]   override val router: Routes = new Routes(
[ERROR]                                     ^
[ERROR] /Users/merlin/dev/play2-maven-router-error/module.finale/src/main/scala/test/ApplicationComponents.scala:5: Unused import
[ERROR] import test.intern.{Routes => InternRoutes}
[ERROR]                     ^
[ERROR] 6 errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] example ............................................ SUCCESS [  0.328 s]
[INFO] module.finale ...................................... FAILURE [  4.782 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.113 s
[INFO] Finished at: 2019-02-19T09:39:23+01:00
[INFO] Final Memory: 36M/134M
[INFO] ------------------------------------------------------------------------
[error] application -

! @7b19mgp9k - Internal server error, for (GET) [/] ->

com.google.code.play2.provider.play26.run.CompilationException: Compilation error[object intern is not a member of package test]
	at com.google.code.play2.provider.play26.run.Reloader.reload(Reloader.java:96)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:123)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:241)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:138)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$26.onPush(Ops.scala:1304)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
```

**Comment by gslowikowski** [comment]
Are you building one of my branches or `master`? Checkout the proper branch.

**Comment by Methrat0n** [comment]
It's been a while and I would really like to thank's you. You have been of great help and I could not have done it without you. Again, thank's a lot.
